# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 02:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='link',
            name='href',
            field=models.URLField(verbose_name=b'\xe9\x93\xbe\xe6\x8e\xa5'),
        ),
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, b'\xe4\xb8\x8a\xe7\xba\xbf'), (2, b'\xe5\x88\xa0\xe9\x99\xa4')], default=1, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=255, verbose_name=b'\xe5\x90\x8d\xe5\xad\x97'),
        ),
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85'),
        ),
        migrations.AlterField(
            model_name='link',
            name='weight',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text=b'\xe6\x9d\x83\xe9\x87\x8d\xe8\xb6\x8a\xe9\xab\x98\xe8\xb6\x8a\xe9\x9d\xa0\xe5\x89\x8d', verbose_name=b'\xe6\x9d\x83\xe9\x87\x8d'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.CharField(max_length=255, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, b'HTML'), (2, b'\xe6\x9c\x80\xe6\x96\xb0\xe6\x96\x87\xe7\xab\xa0'), (3, b'\xe6\x9c\x80\xe7\x83\xad\xe6\x96\x87\xe7\xab\xa0'), (4, b'\xe6\x9c\x80\xe6\x96\xb0\xe8\xaf\x84\xe8\xae\xba')], default=1, verbose_name=b'\xe5\xb1\x95\xe7\xa4\xba\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, b'\xe4\xb8\x8a\xe7\xba\xbf'), (2, b'\xe5\x88\xa0\xe9\x99\xa4')], default=1, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='title',
            field=models.CharField(max_length=255, verbose_name=b'\xe5\x90\x8d\xe5\xad\x97'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85'),
        ),
    ]
